spring.application.name=pensionados
server.servlet.context-path=/api/pensionados/
server.port=8081
# ACCESO A VARIABLES MEDIANTE AZURE KEY VAULT (OBLIGATORIAS) POR VARIABLE DE ENTORNO DE AZURE
# estructura https://<tu-keyvault>.vault.azure.net/
#spring.cloud.azure.keyvault.secret.endpoint=${KEYVAULT_URI}
#spring.cloud.azure.credential.managed-identity-enabled=true

# (OPCIONAL) si se usa autenticacion por ClientId y ClientSecret
#spring.cloud.azure.credential.client-id=${client-id}
#spring.cloud.azure.credential.client-secret=${client-secret}
#spring.cloud.azure.credential.tenant-id=${tenant-id}

azure.activedirectory.client-id=b66fa6e2-78f9-4597-bdbb-a6b33363b992
azure.activedirectory.client-secret=YOUR_CLIENT_SECRET
azure.activedirectory.tenant-id=d36775fa-f481-4695-86f4-41432c8f57af
azure.activedirectory.user-group.allowed-groups=AMP_Prod_Admin,AMP_Prod_Analista,AMP_Prod_Reintegros,AMP_Prod_Autorizacion,AMP_Prod_GestionPerfiles
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d36775fa-f481-4695-86f4-41432c8f57af/v2.0
# Datasource H2
spring.datasource.url=jdbc:h2:mem:pensionadosbd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Datasource SQL SERVER con key vaults
#spring.datasource.transactional.jdbc-url=${db1-connection-string}
#spring.datasource.transactional.username=${db1-username}
#spring.datasource.transactional.password=${db1-password}
#spring.datasource.transactional.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://amp.azure.desa.davivienda.loc 

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d36775fa-f481-4695-86f4-41432c8f57af/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=api://b66fa6e2-78f9-4597-bdbb-a6b33363b992

# Consultas en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auto creacion / actualizacion tablas
spring.jpa.hibernate.ddl-auto=update

# H2 acceso web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# CORS LOCALES
cors.allowed-origins=http://localhost:5173
cors.allowed-headers=Content-Type,Authorization
cors.allowed-methods=GET,PUT,POST,PATCH,DELETE,OPTIONS
cors.exposed-headers=Content-Disposition

# CONFIGURACION DE CORS PARA KEYVAULTS
# cors.allowed-origins=${cors.allowed-origins}
# cors.allowed-headers=${cors.allowed-headers}
# cors.allowed-methods=${cors.allowed-methods}
# cors.exposed-headers=${cors.exposed-headers}

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            tenant-id: YOUR_TENANT_ID
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/"