spring.application.name=pensionados
server.servlet.context-path=/api/pensionados/

# ACCESO A VARIABLES MEDIANTE AZURE KEY VAULT (OBLIGATORIAS) POR VARIABLE DE ENTORNO DE AZURE
# estructura https://<tu-keyvault>.vault.azure.net/
#spring.cloud.azure.keyvault.secret.endpoint=${KEYVAULT_URI}
#spring.cloud.azure.credential.managed-identity-enabled=true

# (OPCIONAL) si se usa autenticacion por ClientId y ClientSecret
#spring.cloud.azure.credential.client-id=${client-id}
#spring.cloud.azure.credential.client-secret=${client-secret}
#spring.cloud.azure.credential.tenant-id=${tenant-id}

# Datasource H2
spring.datasource.url=jdbc:h2:mem:pensionadosbd;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Datasource SQL SERVER con key vaults
#spring.datasource.transactional.jdbc-url=${db1-connection-string}
#spring.datasource.transactional.username=${db1-username}
#spring.datasource.transactional.password=${db1-password}
#spring.datasource.transactional.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Consultas en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auto creacion / actualizacion tablas
spring.jpa.hibernate.ddl-auto=update

# H2 acceso web
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# CORS LOCALES
cors.allowed-origins=http://localhost:5173
cors.allowed-headers=Content-Type,Authorization
cors.allowed-methods=GET,PUT,POST,PATCH,DELETE,OPTIONS
cors.exposed-headers=Content-Disposition

# CONFIGURACION DE CORS PARA KEYVAULTS
# cors.allowed-origins=${cors.allowed-origins}
# cors.allowed-headers=${cors.allowed-headers}
# cors.allowed-methods=${cors.allowed-methods}
# cors.exposed-headers=${cors.exposed-headers}
